"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { waiterSessionHeaders } from "./waiter-session-client";
import type { WaiterReservation } from "./rezerwacje/reservations-employee-client";
type Data = { reservations: WaiterReservation[]; today: string; notice: WaiterReservation | null; preparation: WaiterReservation | null };
const time = new Intl.DateTimeFormat("pl-PL", { hour: "2-digit", minute: "2-digit" });
const dayKey = (value: string) => new Intl.DateTimeFormat("en-CA", { timeZone: "Europe/Warsaw", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date(value));
export default function ReservationReminder() { const [data, setData] = useState<Data | null>(null); const [modal, setModal] = useState<"NOTICE" | "PREPARATION" | null>(null); const [busy, setBusy] = useState(false);
  const load = useCallback(async (show: boolean) => { const response = await fetch("/api/waiter/reservations", { cache: "no-store", headers: waiterSessionHeaders() }).catch(() => null); if (!response?.ok) return; const body = await response.json() as Data; setData(body); if (show) setModal(body.preparation ? "PREPARATION" : body.notice ? "NOTICE" : null); }, []);
  // Hydrate the badge and show reminders only after an explicit PIN login.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(false); const login = () => void load(true); const changed = () => void load(false); window.addEventListener("waiter-session-changed", login); window.addEventListener("reservations-changed", changed); return () => { window.removeEventListener("waiter-session-changed", login); window.removeEventListener("reservations-changed", changed); }; }, [load]);
  async function action(item: WaiterReservation, name: "ACK_2H" | "TABLE_READY" | "REQUEST_READY") { setBusy(true); await fetch("/api/waiter/reservations", { method: "POST", headers: waiterSessionHeaders({ "content-type": "application/json" }), body: JSON.stringify({ action: name, id: item.id }) }); await load(false); if (name === "ACK_2H") setModal(null); setBusy(false); }
  const item = modal === "PREPARATION" ? data?.preparation : data?.notice; const todayCount = data?.reservations.filter((reservation) => dayKey(reservation.startsAt) === data.today).length ?? 0;
  return <><Link className="waiter-reservations-floating" href="/kelner/rezerwacje">Rezerwacje{todayCount > 0 && <b>{todayCount}</b>}</Link>{modal && item && <div className="reservation-reminder-backdrop"><section className={modal === "PREPARATION" ? "is-urgent" : ""}><span>{modal === "PREPARATION" ? "DO REZERWACJI ZOSTAŁA MAKSYMALNIE GODZINA" : "REZERWACJA ZA MNIEJ NIŻ 2 GODZINY"}</span><h2>{item.guestName || "Rezerwacja bez nazwy"}{item.partySize !== null ? ` · ${item.partySize} os.` : ""}</h2><strong>{time.format(new Date(item.startsAt))}{item.location ? ` · ${item.location}` : ""}</strong>{item.specialRequest && <p><b>Notatka:</b> {item.specialRequest}</p>}{modal === "NOTICE" ? <footer><button disabled={busy} onClick={() => void action(item, "ACK_2H")}>OK, przyjąłem/am informację</button><Link href="/kelner/rezerwacje">Pokaż rezerwację</Link></footer> : <><div className="reservation-ready-actions">{item.specialRequest && <button disabled={busy || Boolean(item.specialRequestReadyAt)} onClick={() => void action(item, "REQUEST_READY")}>{item.specialRequestReadyAt ? "✓ Życzenie przygotowane" : "Potwierdź przygotowanie życzenia"}</button>}<button disabled={busy || Boolean(item.tableReadyAt)} onClick={() => void action(item, "TABLE_READY")}>{item.tableReadyAt ? "✓ Stolik gotowy" : "Stolik gotowy"}</button></div><footer><button onClick={() => setModal(null)}>Zamknij do następnego logowania</button><Link href="/kelner/rezerwacje">Otwórz wszystkie rezerwacje</Link></footer></>}</section></div>}</>;
}
