"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { addDays, mondayFor, WEEK_DAYS, weekDates } from "../../../lib/workforce";
import AdminSectionHeader from "../admin-section-header";

type Employee = { dotykackaId: string; name: string; includeInSchedule: boolean };
type Availability = { employeeDotykackaId: string; employeeName: string; minShifts: number; maxShifts: number; days: Array<{ date: string; available: boolean; from: string | null; to: string | null; note: string | null }> };
type Shift = { id?: number; employeeDotykackaId: string; employeeName?: string; workDate: string; startsAt?: string; endsAt?: string; from: string; to: string; note: string };
type Schedule = { id: number; status: "DRAFT" | "PUBLISHED"; version: number; openingHours: Opening[]; publishedAt: string | null };
type Opening = { date: string; closed: boolean; from: string | null; to: string | null };
type Correction = { id: number; employeeName: string; workDate: string; requestedStart: string; requestedEnd: string; reason: string };
type Entry = { id: number; employeeDotykackaId: string; employeeName: string; startedAt: string; endedAt: string | null; workedMinutes: number | null; status: string };
type CalendarEvent = { uid: string; title: string; startsAt: string; endsAt: string | null; allDay: boolean };
type Reservation = { id: number; guestName: string | null; partySize: number | null; startsAt: string; endsAt: string; location: string | null; specialRequest: string | null };
type Data = { employees: Employee[]; settlementEmployees: Employee[]; availability: Availability[]; schedule: Schedule | null; shifts: Array<Omit<Shift, "from" | "to"> & { startsAt: string; endsAt: string }>; corrections: Correction[]; entries: Entry[]; events: CalendarEvent[]; reservations: Reservation[]; calendar: { connected: boolean; name: string; error: string | null } };

const polishDate = new Intl.DateTimeFormat("pl-PL", { weekday: "short", day: "numeric", month: "short" });
const polishTime = new Intl.DateTimeFormat("pl-PL", { hour: "2-digit", minute: "2-digit" });
const inputTime = (value: string) => new Intl.DateTimeFormat("en-GB", { timeZone: "Europe/Warsaw", hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).format(new Date(value));
const emptyOpenings = (weekStart: string): Opening[] => weekDates(weekStart).map((date) => ({ date, closed: false, from: "08:00", to: "22:00" }));

export default function WorkforceAdminClient() {
  const [weekStart, setWeekStart] = useState(mondayFor()); const [data, setData] = useState<Data | null>(null);
  const [shifts, setShifts] = useState<Shift[]>([]); const [openings, setOpenings] = useState<Opening[]>(emptyOpenings(weekStart));
  const [busy, setBusy] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const [calendarForm, setCalendarForm] = useState({ name: "Kalendarz wydarzeń", url: "" });

  const load = useCallback(async () => {
    setError(""); const response = await fetch(`/api/admin/workforce?weekStart=${weekStart}`, { cache: "no-store" }); const body = await response.json().catch(() => ({})) as Data & { error?: string };
    if (!response.ok) setError(body.error ?? "Nie udało się pobrać grafiku."); else { setData(body); setOpenings(body.schedule?.openingHours?.length ? body.schedule.openingHours : emptyOpenings(weekStart)); setShifts(body.shifts.map((shift) => ({ ...shift, from: inputTime(shift.startsAt), to: inputTime(shift.endsAt), note: shift.note ?? "" }))); setCalendarForm((current) => ({ ...current, name: body.calendar.name })); }
  }, [weekStart]);
  // Initial administrator planner hydration.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); }, [load]);

  const dates = weekDates(weekStart); const employeeById = new Map((data?.employees ?? []).map((employee) => [employee.dotykackaId, employee]));
  const monthly = useMemo(() => { const result = new Map<string, number>(); for (const entry of data?.entries ?? []) result.set(entry.employeeDotykackaId, (result.get(entry.employeeDotykackaId) ?? 0) + (entry.workedMinutes ?? 0)); return result; }, [data]);
  function addShift(date = dates[0]) { const employee = data?.employees[0]; if (!employee) return; setShifts((current) => [...current, { employeeDotykackaId: employee.dotykackaId, employeeName: employee.name, workDate: date, from: "09:00", to: "17:00", note: "" }]); }
  function updateShift(index: number, patch: Partial<Shift>) { setShifts((current) => current.map((shift, position) => position === index ? { ...shift, ...patch } : shift)); }
  function updateOpening(index: number, patch: Partial<Opening>) { setOpenings((current) => current.map((opening, position) => position === index ? { ...opening, ...patch } : opening)); }

  async function savePlan(publish = false) {
    if (busy) return; setBusy(publish ? "publish" : "save"); setError(""); setMessage("");
    const save = await fetch("/api/admin/workforce", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "SAVE_PLAN", weekStart, openingHours: openings, shifts: shifts.map(({ employeeDotykackaId, workDate, from, to, note }) => ({ employeeDotykackaId, workDate, from, to, note })) }) });
    const saveBody = await save.json().catch(() => ({})) as { error?: string };
    if (!save.ok) setError(saveBody.error ?? "Nie udało się zapisać planu.");
    else if (publish) { const response = await fetch("/api/admin/workforce", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "PUBLISH", weekStart }) }); const body = await response.json().catch(() => ({})) as { error?: string }; if (!response.ok) setError(body.error ?? "Nie udało się opublikować grafiku."); else setMessage("Grafik opublikowany. Pracownicy zobaczą swoje zmiany, a kalendarze wymagające odświeżenia zostaną oznaczone."); }
    else setMessage("Szkic grafiku zapisany.");
    await load(); setBusy("");
  }

  async function reviewCorrection(id: number, decision: "APPROVE" | "REJECT") { setBusy(`correction:${id}`); const response = await fetch("/api/admin/workforce", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "REVIEW_CORRECTION", weekStart, id, decision }) }); const body = await response.json().catch(() => ({})) as { error?: string }; if (!response.ok) setError(body.error ?? "Nie udało się rozpatrzyć wniosku."); else setMessage(decision === "APPROVE" ? "Godziny zostały dopisane." : "Wniosek odrzucony."); await load(); setBusy(""); }
  async function saveCalendar(event: FormEvent) { event.preventDefault(); setBusy("calendar"); const response = await fetch("/api/admin/workforce", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "SAVE_CALENDAR", ...calendarForm }) }); const body = await response.json().catch(() => ({})) as { error?: string }; if (!response.ok) setError(body.error ?? "Nie udało się połączyć kalendarza."); else setMessage(calendarForm.url ? "Kalendarz wydarzeń został połączony." : "Połączenie kalendarza usunięte."); await load(); setBusy(""); }

  return <main className="workforce-admin">
    <AdminSectionHeader eyebrow="Zespół i czas pracy" title="Grafik pracy" links={[{ href: "/admin/waiters", label: "Pracownicy i dostępy" }]}/>
    <section className="workforce-week-nav"><button onClick={() => setWeekStart(addDays(weekStart, -7))}>← Poprzedni</button><div><span>TYDZIEŃ</span><strong>{polishDate.format(new Date(`${weekStart}T12:00:00Z`))} — {polishDate.format(new Date(`${addDays(weekStart, 6)}T12:00:00Z`))}</strong>{data?.schedule && <small>{data.schedule.status === "PUBLISHED" ? `Opublikowany · wersja ${data.schedule.version}` : "Szkic"}</small>}</div><button onClick={() => setWeekStart(addDays(weekStart, 7))}>Następny →</button></section>
    {(message || error) && <p className={`workforce-status${error ? " is-error" : ""}`}>{error || message}</p>}
    <section className="workforce-admin-grid">
      <article className="workforce-panel workforce-availability"><header><div><span>KROK 1</span><h2>Dyspozycje pracowników</h2></div><b>{data?.availability.length ?? 0}/{data?.employees.length ?? 0}</b></header><div className="workforce-table"><div className="is-head"><b>Pracownik</b>{dates.map((date, index) => <span key={date}>{WEEK_DAYS[index].slice(0, 3)}<small>{date.slice(8)}</small></span>)}<b>Zmiany</b></div>{data?.employees.map((employee) => { const availability = data.availability.find((row) => row.employeeDotykackaId === employee.dotykackaId); return <div key={employee.dotykackaId}><strong>{employee.name}</strong>{dates.map((date) => { const day = availability?.days.find((row) => row.date === date); return <span key={date} className={day?.available ? "is-available" : "is-unavailable"} title={day?.note ?? ""}>{day?.available ? <>{day.from && <small>{day.from}–{day.to}</small>}✓</> : "—"}</span>})}<b>{availability ? `${availability.minShifts}–${availability.maxShifts}` : "brak"}</b></div>})}</div></article>
      <article className="workforce-panel workforce-context"><header><div><span>KONTEKST DNIA</span><h2>Godziny lokalu, rezerwacje i wydarzenia</h2></div></header><div className="workforce-opening-list">{openings.map((opening, index) => <div key={opening.date}><b>{WEEK_DAYS[index]}</b><label><input type="checkbox" checked={opening.closed} onChange={(event) => updateOpening(index, { closed: event.target.checked })}/> zamknięte</label><input type="time" disabled={opening.closed} value={opening.from ?? ""} onChange={(event) => updateOpening(index, { from: event.target.value })}/><span>—</span><input type="time" disabled={opening.closed} value={opening.to ?? ""} onChange={(event) => updateOpening(index, { to: event.target.value })}/></div>)}</div><div className="workforce-events workforce-reservation-context"><h3>Rezerwacje w tym tygodniu</h3>{data?.reservations.map((reservation) => <div key={reservation.id}><time>{polishDate.format(new Date(reservation.startsAt))} · {polishTime.format(new Date(reservation.startsAt))}–{polishTime.format(new Date(reservation.endsAt))}</time><strong>{reservation.guestName || "Rezerwacja bez nazwy"}{reservation.partySize !== null ? ` · ${reservation.partySize} os.` : ""}</strong><span>{[reservation.location, reservation.specialRequest].filter(Boolean).join(" · ") || "Brak dodatkowych informacji"}</span></div>)}{!data?.reservations.length && <p>Brak rezerwacji w tym tygodniu.</p>}</div><div className="workforce-events"><h3>Wydarzenia · tylko dla administratora</h3>{data?.events.map((event) => <div key={event.uid}><time>{polishDate.format(new Date(event.startsAt))}{!event.allDay && ` · ${polishTime.format(new Date(event.startsAt))}`}</time><strong>{event.title}</strong><span>Wymagane minimum 2 osoby na zmianie.</span></div>)}{!data?.events.length && <p>{data?.calendar.connected ? data.calendar.error || "Brak wydarzeń w tym tygodniu." : "Połącz współdzielony kalendarz poniżej."}</p>}</div></article>
    </section>
    <section className="workforce-panel workforce-planner"><header><div><span>KROK 2</span><h2>Ułóż i opublikuj grafik</h2></div><button className="workforce-add-shift" disabled={!data?.employees.length} onClick={() => addShift()}>+ Dodaj zmianę</button></header>{!data?.employees.length && <p className="workforce-empty">Brak pracowników włączonych do planowania. Zmień ustawienie w panelu „Pracownicy”.</p>}<div className="workforce-shift-list">{shifts.map((shift, index) => { const excluded = !employeeById.has(shift.employeeDotykackaId); return <div key={`${shift.id ?? "new"}-${index}`} className={excluded ? "is-excluded" : ""}><select value={shift.employeeDotykackaId} onChange={(event) => updateShift(index, { employeeDotykackaId: event.target.value, employeeName: employeeById.get(event.target.value)?.name })}>{excluded && <option value={shift.employeeDotykackaId}>{shift.employeeName ?? "Pracownik"} — wyłączony z planowania</option>}{data?.employees.map((employee) => <option key={employee.dotykackaId} value={employee.dotykackaId}>{employee.name}</option>)}</select><input type="date" min={dates[0]} max={dates[6]} value={shift.workDate} onChange={(event) => updateShift(index, { workDate: event.target.value })}/><input type="time" value={shift.from} onChange={(event) => updateShift(index, { from: event.target.value })}/><span>—</span><input type="time" value={shift.to} onChange={(event) => updateShift(index, { to: event.target.value })}/><input value={shift.note} placeholder={excluded ? "Usuń zmianę albo wybierz inną osobę" : "Notatka"} onChange={(event) => updateShift(index, { note: event.target.value })}/><button aria-label="Usuń zmianę" onClick={() => setShifts((current) => current.filter((_, position) => position !== index))}>×</button></div>; })}</div>{!shifts.length && data?.employees.length ? <p className="workforce-empty">Nie dodano jeszcze żadnej zmiany.</p> : null}<footer><button disabled={Boolean(busy)} onClick={() => void savePlan(false)}>Zapisz szkic</button><button className="is-primary" disabled={Boolean(busy)} onClick={() => void savePlan(true)}>{busy === "publish" ? "Publikuję…" : data?.schedule?.status === "PUBLISHED" ? "Opublikuj aktualizację" : "Opublikuj grafik"}</button></footer></section>
    <section className="workforce-admin-grid">
      <article className="workforce-panel"><header><div><span>KONTROLA CZASU</span><h2>Miesięczne godziny</h2></div></header><div className="workforce-hours-list">{data?.settlementEmployees.map((employee) => <div key={employee.dotykackaId}><strong>{employee.name}{!employee.includeInSchedule && <small> · poza grafikiem</small>}</strong><b>{Math.floor((monthly.get(employee.dotykackaId) ?? 0) / 60)} h {(monthly.get(employee.dotykackaId) ?? 0) % 60} min</b></div>)}</div></article>
      <article className="workforce-panel"><header><div><span>WYMAGA DECYZJI</span><h2>Wnioski o dopisanie godzin</h2></div><b>{data?.corrections.length ?? 0}</b></header><div className="workforce-corrections">{data?.corrections.map((request) => <div key={request.id}><strong>{request.employeeName}</strong><span>{request.workDate} · {polishTime.format(new Date(request.requestedStart))}–{polishTime.format(new Date(request.requestedEnd))}</span><p>{request.reason}</p><footer><button disabled={Boolean(busy)} onClick={() => void reviewCorrection(request.id, "REJECT")}>Odrzuć</button><button disabled={Boolean(busy)} onClick={() => void reviewCorrection(request.id, "APPROVE")}>Zatwierdź i dopisz</button></footer></div>)}{!data?.corrections.length && <p>Brak wniosków oczekujących.</p>}</div></article>
    </section>
    <section className="workforce-panel workforce-calendar-config workforce-calendar-standalone"><header><div><span>PLANOWANE WYDARZENIA</span><h2>Współdzielony kalendarz</h2></div></header><p>Wklej prywatny adres subskrypcji iCal/ICS. Adres jest szyfrowany, wydarzenia widzi wyłącznie administrator podczas planowania.</p><form onSubmit={saveCalendar}><label>Nazwa<input value={calendarForm.name} onChange={(event) => setCalendarForm({ ...calendarForm, name: event.target.value })}/></label><label>Adres ICS<input type="url" value={calendarForm.url} placeholder={data?.calendar.connected ? "Połączono — wklej adres tylko, aby go zmienić" : "https://…/calendar.ics"} onChange={(event) => setCalendarForm({ ...calendarForm, url: event.target.value })}/></label><button disabled={Boolean(busy)}>Zapisz połączenie</button></form></section>
  </main>;
}
