"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { clearWaiterSessionToken, waiterSessionHeaders } from "../waiter-session-client";
import { WaiterSectionHeader } from "../staff-navigation";
export type WaiterReservation = { id: number; guestName: string | null; guestContact: string | null; partySize: number | null; startsAt: string; endsAt: string; location: string | null; specialRequest: string | null; tableReadyAt: string | null; tableReadyByName: string | null; specialRequestReadyAt: string | null; specialRequestReadyByName: string | null; addedByName: string };
type Data = { employee: { name: string }; reservations: WaiterReservation[]; today: string };
const date = new Intl.DateTimeFormat("pl-PL", { weekday: "long", day: "numeric", month: "long" }); const time = new Intl.DateTimeFormat("pl-PL", { hour: "2-digit", minute: "2-digit" });
const localDate = (value: string) => new Intl.DateTimeFormat("en-CA", { timeZone: "Europe/Warsaw", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date(value));
export default function ReservationsEmployeeClient() { const [data, setData] = useState<Data | null>(null); const [openForm, setOpenForm] = useState(false); const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const load = useCallback(async () => { const response = await fetch("/api/waiter/reservations", { cache: "no-store", headers: waiterSessionHeaders() }); if (response.status === 401) { clearWaiterSessionToken(); window.location.replace("/kelner"); return; } const body = await response.json().catch(() => ({})) as Data & { error?: string }; if (!response.ok) setError(body.error ?? "Nie udało się pobrać rezerwacji."); else setData(body); }, []);
  // Initial employee reservation hydration.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); }, [load]);
  async function action(id: number, actionName: "TABLE_READY" | "REQUEST_READY" | "CANCEL") { if (actionName === "CANCEL" && !confirm("Czy na pewno anulować tę rezerwację?")) return; setBusy(`${actionName}:${id}`); setError(""); const response = await fetch("/api/waiter/reservations", { method: "POST", headers: waiterSessionHeaders({ "content-type": "application/json" }), body: JSON.stringify({ action: actionName, id }) }); const body = await response.json().catch(() => ({})) as { error?: string; calendarWarning?: string | null }; if (!response.ok) setError(body.error ?? "Nie udało się zapisać zmiany."); else { setMessage(body.calendarWarning ? `Zmiana zapisana, ale iCloud zwrócił błąd: ${body.calendarWarning}` : actionName === "CANCEL" ? "Rezerwacja anulowana również w iCloud." : "Status przygotowania zapisany."); await load(); window.dispatchEvent(new Event("reservations-changed")); } setBusy(""); }
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy("create"); setError(""); const form = event.currentTarget; const values = Object.fromEntries(new FormData(form)); const response = await fetch("/api/waiter/reservations", { method: "POST", headers: waiterSessionHeaders({ "content-type": "application/json" }), body: JSON.stringify({ action: "CREATE", ...values }) }); const body = await response.json().catch(() => ({})) as { error?: string; calendarWarning?: string | null }; if (!response.ok) setError(body.error ?? "Nie udało się dodać rezerwacji."); else { form.reset(); setOpenForm(false); setMessage(body.calendarWarning ? `Rezerwacja zapisana, ale iCloud zwrócił błąd: ${body.calendarWarning}` : "Rezerwacja zapisana również w iCloud."); await load(); } setBusy(""); }
  const today = data?.reservations.filter((item) => localDate(item.startsAt) === data.today) ?? []; const upcoming = data?.reservations.filter((item) => localDate(item.startsAt) !== data.today) ?? [];
  return <main className="waiter-reservations"><WaiterSectionHeader eyebrow="Goście i stoliki" title="Rezerwacje" employeeName={data?.employee.name}/>{(message || error) && <p className={`waiter-reservation-status${error ? " is-error" : ""}`}>{error || message}</p>}<section className="waiter-reservation-hero"><div><span>DZISIAJ</span><h1>Rezerwacje na zmianę</h1><p>Najpierw przygotuj stolik i każde specjalne życzenie, potem potwierdź ich gotowość.</p></div><b>{today.length}</b><button onClick={() => setOpenForm(!openForm)}>{openForm ? "Zamknij formularz" : "+ Przyjmij rezerwację"}</button></section>
    {openForm && <form className="waiter-reservation-form" onSubmit={create}><label>Imię gościa<input required name="guestName"/></label><label>Telefon lub e-mail<input required name="guestContact"/></label><label>Osoby<input required type="number" min="1" max="200" name="partySize" defaultValue="2"/></label><label>Data<input required type="date" name="date" defaultValue={data?.today}/></label><label>Od<input required type="time" name="from"/></label><label>Do<input required type="time" name="to"/></label><label className="is-wide">Miejsce / stolik<input required name="location" placeholder="np. stolik przy oknie"/></label><label className="is-wide">Specjalne życzenie<textarea name="specialRequest" placeholder="np. krzesełko, tort, alergia…"/></label><button disabled={Boolean(busy)}>Zapisz rezerwację</button></form>}
    <section className="waiter-reservation-today">{today.map((item) => <Reservation item={item} key={item.id} busy={busy} action={action}/>)}{!today.length && <p>Dzisiaj nie ma rezerwacji.</p>}</section><section className="waiter-reservation-next"><header><h2>Kolejne rezerwacje</h2><b>{upcoming.length}</b></header>{upcoming.map((item) => <Reservation item={item} key={item.id} busy={busy} action={action}/>)}{!upcoming.length && <p>Brak kolejnych rezerwacji.</p>}</section>
  </main>;
}
function Reservation({ item, busy, action }: { item: WaiterReservation; busy: string; action: (id: number, action: "TABLE_READY" | "REQUEST_READY" | "CANCEL") => Promise<void> }) { return <article className={item.tableReadyAt && (!item.specialRequest || item.specialRequestReadyAt) ? "is-complete" : ""}><time><b>{time.format(new Date(item.startsAt))}</b><span>{date.format(new Date(item.startsAt))}</span><small>do {time.format(new Date(item.endsAt))}</small></time><div><h3>{item.guestName || "Rezerwacja bez nazwy"}{item.partySize !== null ? ` · ${item.partySize} os.` : ""}</h3><strong>{item.location || "Miejsce niepodane"}</strong>{item.guestContact ? <a href={`tel:${item.guestContact.replace(/\s/g, "")}`}>{item.guestContact}</a> : <span>Kontakt niepodany</span>}{item.specialRequest && <p><b>Notatka:</b> {item.specialRequest}</p>}<small>Rezerwację dodał/a: {item.addedByName}</small></div><aside>{item.specialRequest && <button disabled={Boolean(busy) || Boolean(item.specialRequestReadyAt)} onClick={() => void action(item.id, "REQUEST_READY")}>{item.specialRequestReadyAt ? `✓ Życzenie gotowe · ${item.specialRequestReadyByName}` : "Potwierdź przygotowanie życzenia"}</button>}<button className="is-ready" disabled={Boolean(busy) || Boolean(item.tableReadyAt)} onClick={() => void action(item.id, "TABLE_READY")}>{item.tableReadyAt ? `✓ Stolik gotowy · ${item.tableReadyByName}` : "Stolik gotowy"}</button><button className="is-cancel" disabled={Boolean(busy)} onClick={() => void action(item.id, "CANCEL")}>Anuluj rezerwację</button></aside></article> }
