"use client";
import { FormEvent, useCallback, useEffect, useRef, useState } from "react";
import AdminSectionHeader from "../admin-section-header";
type Reservation = { id: number; source: string; guestName: string | null; guestContact: string | null; partySize: number | null; startsAt: string; endsAt: string; location: string | null; specialRequest: string | null; status: string; tableReadyAt: string | null; specialRequestReadyAt: string | null; addedByName: string };
type Data = { reservations: Reservation[]; calendar: { connected: boolean; name: string; subscriptionUrl: string; writeBackConnected: boolean; writeCalendarName: string } };
const day = new Intl.DateTimeFormat("pl-PL", { weekday: "long", day: "numeric", month: "long" }); const time = new Intl.DateTimeFormat("pl-PL", { hour: "2-digit", minute: "2-digit" });
const localDate = (value: string) => new Intl.DateTimeFormat("en-CA", { timeZone: "Europe/Warsaw", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date(value)); const localTime = (value: string) => new Intl.DateTimeFormat("en-GB", { timeZone: "Europe/Warsaw", hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).format(new Date(value));
export default function ReservationsAdminClient() {
  const [data, setData] = useState<Data | null>(null); const [editing, setEditing] = useState<Reservation | null>(null); const [busy, setBusy] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [calendar, setCalendar] = useState({ name: "Rezerwacje Atelier Café", url: "" }); const [icloud, setIcloud] = useState({ username: "", password: "", calendarName: "Rezerwacje stoliki CAFE" }); const editorRef = useRef<HTMLElement | null>(null);
  const load = useCallback(async () => { const response = await fetch("/api/admin/reservations", { cache: "no-store" }); const body = await response.json().catch(() => ({})) as Data & { error?: string }; if (!response.ok) setError(body.error ?? "Nie udało się pobrać rezerwacji."); else { setData(body); setCalendar((current) => ({ ...current, name: body.calendar.name })); setIcloud((current) => ({ ...current, calendarName: body.calendar.writeCalendarName })); } }, []);
  // Initial administrator reservation hydration.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { if (editing) editorRef.current?.scrollIntoView({ behavior: "smooth", block: "start" }); }, [editing]);
  function startEditing(item: Reservation) { setError(""); setMessage(`Edytujesz rezerwację: ${item.guestName || "bez nazwy"}.`); setEditing(item); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const values = Object.fromEntries(new FormData(form)); setBusy("reservation"); setError(""); const response = await fetch("/api/admin/reservations", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: editing ? "UPDATE" : "CREATE", id: editing?.id, ...values }) }); const body = await response.json().catch(() => ({})) as { error?: string; calendarWarning?: string | null }; if (!response.ok) setError(body.error ?? "Nie udało się zapisać rezerwacji."); else { form.reset(); setEditing(null); setMessage(body.calendarWarning ? `${editing ? "Rezerwacja zaktualizowana" : "Rezerwacja zapisana"}, ale iCloud zwrócił błąd: ${body.calendarWarning}` : editing ? "Rezerwacja zaktualizowana również w iCloud." : "Rezerwacja zapisana również w iCloud."); await load(); } setBusy(""); }
  async function cancel(item: Reservation) { if (!confirm(`Anulować rezerwację ${item.guestName || "bez nazwy"}?`)) return; setBusy(`cancel:${item.id}`); setError(""); const response = await fetch("/api/admin/reservations", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "CANCEL", id: item.id }) }); const body = await response.json().catch(() => ({})) as { error?: string; calendarWarning?: string | null }; if (!response.ok) setError(body.error ?? "Nie udało się anulować rezerwacji."); else { setMessage(body.calendarWarning ? `Rezerwacja anulowana, ale iCloud zwrócił błąd: ${body.calendarWarning}` : "Rezerwacja anulowana również w iCloud."); await load(); } setBusy(""); }
  async function saveCalendar(event: FormEvent) { event.preventDefault(); setBusy("calendar"); const response = await fetch("/api/admin/reservations", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "SAVE_CALENDAR", ...calendar }) }); const body = await response.json().catch(() => ({})) as { error?: string }; if (!response.ok) setError(body.error ?? "Nie udało się zapisać kalendarza."); else { setMessage("Połączenie kalendarza zapisane."); await load(); } setBusy(""); }
  async function syncCalendar() { setBusy("sync"); const response = await fetch("/api/admin/reservations", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "SYNC_CALENDAR" }) }); const body = await response.json().catch(() => ({})) as { error?: string; imported?: number }; if (!response.ok) setError(body.error ?? "Nie udało się zsynchronizować kalendarza."); else { setMessage(`Synchronizacja zakończona: ${body.imported ?? 0} rezerwacji.`); await load(); } setBusy(""); }
  async function connectIcloud(event: FormEvent) { event.preventDefault(); setBusy("icloud"); setError(""); const response = await fetch("/api/admin/reservations", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "CONNECT_ICLOUD", ...icloud }) }); const body = await response.json().catch(() => ({})) as { error?: string; calendarName?: string; exported?: number; failed?: number }; if (!response.ok) setError(body.error ?? "Nie udało się połączyć zapisu z iCloud."); else { setIcloud((current) => ({ ...current, username: "", password: "", calendarName: body.calendarName ?? current.calendarName })); setMessage(`Połączono zapis z kalendarzem „${body.calendarName}”. Wysłano ${body.exported ?? 0} rezerwacji${body.failed ? `, błędy: ${body.failed}` : ""}.`); await load(); } setBusy(""); }
  const today = localDate(new Date().toISOString()); const active = (data?.reservations ?? []).filter((item) => item.status === "BOOKED"); const todayRows = active.filter((item) => localDate(item.startsAt) === today); const upcoming = active.filter((item) => localDate(item.startsAt) !== today);
  const defaults = editing ? { guestName: editing.guestName ?? "", guestContact: editing.guestContact ?? "", partySize: editing.partySize ?? "", date: localDate(editing.startsAt), from: localTime(editing.startsAt), to: localTime(editing.endsAt), location: editing.location ?? "", specialRequest: editing.specialRequest ?? "" } : { guestName: "", guestContact: "", partySize: 2, date: today, from: "18:00", to: "20:00", location: "", specialRequest: "" };
  return <main className="reservations-admin"><AdminSectionHeader eyebrow="Goście i stoliki" title="Rezerwacje"/>{(message || error) && <p className={`reservation-status${error ? " is-error" : ""}`}>{error || message}</p>}
    <section className="reservation-today"><header><div><span>DZISIAJ</span><h2>{day.format(new Date())}</h2></div><b>{todayRows.length}</b></header><div>{todayRows.map((item) => <ReservationCard key={item.id} item={item} onEdit={() => startEditing(item)} onCancel={() => void cancel(item)}/>)}{!todayRows.length && <p>Na dzisiaj nie ma zapisanych rezerwacji.</p>}</div></section>
    <section className="reservation-admin-grid"><article ref={editorRef} className={`reservation-panel reservation-editor${editing ? " is-editing" : ""}`}><header><span>{editing ? "EDYCJA REZERWACJI" : "NOWA REZERWACJA"}</span><h2>{editing ? editing.guestName || "Rezerwacja bez nazwy" : "Zapisz komplet informacji"}</h2></header><form key={editing?.id ?? "new"} onSubmit={submit}><label>Imię gościa<input required={!editing} name="guestName" defaultValue={defaults.guestName}/></label><label>Kontakt do gościa<input required={!editing} name="guestContact" defaultValue={defaults.guestContact} placeholder="telefon lub e-mail"/></label><label>Liczba osób<input required={!editing} type="number" min="1" max="200" name="partySize" defaultValue={defaults.partySize}/></label><label>Data<input required type="date" name="date" defaultValue={defaults.date}/></label><label>Od<input required type="time" name="from" defaultValue={defaults.from}/></label><label>Do<input required type="time" name="to" defaultValue={defaults.to}/></label><label className="is-wide">Miejsce / stolik<input required={!editing} name="location" defaultValue={defaults.location} placeholder="np. stolik przy oknie, sala dolna"/></label><label className="is-wide">Notatka<textarea name="specialRequest" defaultValue={defaults.specialRequest} placeholder="np. krzesełko, tort, alergia albo treść z kalendarza…"/></label><footer>{editing && <button type="button" onClick={() => setEditing(null)}>Anuluj edycję</button>}<button disabled={Boolean(busy)}>{editing ? "Zapisz zmiany" : "Dodaj rezerwację"}</button></footer></form></article>
      <article className="reservation-panel reservation-calendar"><header><span>KALENDARZ NA IPHONE</span><h2>Jedna lista rezerwacji dla wszystkich</h2></header><p>Adres ICS pobiera wpisy z kalendarza „Rezerwacje stoliki CAFE” automatycznie co około 2 minuty.</p><form onSubmit={saveCalendar}><label>Nazwa w aplikacji<input value={calendar.name} onChange={(event) => setCalendar({ ...calendar, name: event.target.value })}/></label><label>Prywatny adres ICS istniejącego kalendarza<input type="url" value={calendar.url} placeholder={data?.calendar.connected ? "Połączono — wpisz tylko, aby zmienić" : "https://…"} onChange={(event) => setCalendar({ ...calendar, url: event.target.value })}/></label><button>Zapisz odczyt</button></form><button type="button" disabled={!data?.calendar.connected || Boolean(busy)} onClick={() => void syncCalendar()}>{busy === "sync" ? "Synchronizuję…" : "Odśwież rezerwacje teraz"}</button><section className="reservation-caldav"><h3>Zapis z aplikacji bezpośrednio do iCloud</h3>{data?.calendar.writeBackConnected ? <p className="is-connected">✓ Połączono z „{data.calendar.writeCalendarName}”. Wszystkie osoby korzystają dalej z obecnego kalendarza.</p> : <p className="is-warning">⚠ Zapis do iCloud nie jest połączony. Rezerwacje utworzone w aplikacji — w tym test o 18:00 — nie pojawią się we wspólnym kalendarzu, dopóki właściciel nie wykona tego jednorazowego połączenia.</p>}<form onSubmit={connectIcloud}><label>Adres konta Apple<input required type="email" autoComplete="username" value={icloud.username} onChange={(event) => setIcloud({ ...icloud, username: event.target.value })}/></label><label>Hasło przeznaczone dla aplikacji<input required type="password" autoComplete="new-password" value={icloud.password} onChange={(event) => setIcloud({ ...icloud, password: event.target.value })}/></label><label>Nazwa kalendarza iCloud<input required value={icloud.calendarName} onChange={(event) => setIcloud({ ...icloud, calendarName: event.target.value })}/></label><button disabled={Boolean(busy)}>{busy === "icloud" ? "Łączę i wysyłam…" : data?.calendar.writeBackConnected ? "Zmień połączenie iCloud" : "Połącz zapis iCloud"}</button></form></section></article>
    </section>
    <section className="reservation-upcoming"><header><span>KOLEJNE REZERWACJE</span><h2>Nadchodzące terminy</h2></header><div>{upcoming.map((item) => <ReservationCard key={item.id} item={item} onEdit={() => startEditing(item)} onCancel={() => void cancel(item)}/>)}{!upcoming.length && <p>Brak kolejnych rezerwacji.</p>}</div></section>
  </main>;
}
function ReservationCard({ item, onEdit, onCancel }: { item: Reservation; onEdit: () => void; onCancel: () => void }) { const details = [item.location, item.guestContact].filter(Boolean).join(" · "); return <article className={item.tableReadyAt ? "is-ready" : ""}><time><b>{time.format(new Date(item.startsAt))}</b><span>{day.format(new Date(item.startsAt))}</span></time><div><strong>{item.guestName || "Rezerwacja bez nazwy"}{item.partySize !== null ? ` · ${item.partySize} os.` : ""}</strong><span>{details || "Brak miejsca i kontaktu"}</span>{item.specialRequest && <p><b>Notatka:</b> {item.specialRequest} {item.specialRequestReadyAt && <em>✓ przygotowane</em>}</p>}<small>Dodał/a: {item.addedByName}{item.source === "ICAL" ? " · import" : ""}</small></div><aside>{item.tableReadyAt && <b>✓ stolik gotowy</b>}<button type="button" onClick={onEdit}>Edytuj</button><button type="button" onClick={onCancel}>Anuluj</button></aside></article> }
